uploads = []
generated = []

[[outputs]]
id = "-nGYbNuABihHDarIXo_Tp"
uri = "file://validador-docs.tar.gz"
type = "unspecified"
title = "Validador de Docs — Código Fonte"

[[outputs]]
id = "RJGICSN4E8T7Fq_wWrqXP"
uri = "file://validador-docs-v2.tar.gz"
type = "unspecified"
title = "Validador de Docs — Código Atualizado"
